//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDetails
    {
        public long ID { get; set; }
        public Nullable<long> Team_ID { get; set; }
        public string GameType { get; set; }
        public string GameRole { get; set; }
        public Nullable<long> List_ID { get; set; }
    
        public virtual GameList GameList { get; set; }
        public virtual TeamList TeamList { get; set; }
    }
}
