//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NEW2101Entities1 : DbContext
    {
        public NEW2101Entities1()
            : base("name=NEW2101Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountData> AccountData { get; set; }
        public virtual DbSet<Checkin> Checkin { get; set; }
        public virtual DbSet<EquipmentList> EquipmentList { get; set; }
        public virtual DbSet<EquipmentLoan> EquipmentLoan { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<GameDetails> GameDetails { get; set; }
        public virtual DbSet<GameList> GameList { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PlanDetails> PlanDetails { get; set; }
        public virtual DbSet<PlayerData> PlayerData { get; set; }
        public virtual DbSet<PlayerList> PlayerList { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeamList> TeamList { get; set; }
        public virtual DbSet<TrainingPlan> TrainingPlan { get; set; }
    }
}
