//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerData
    {
        public long ID { get; set; }
        public Nullable<long> Player_ID { get; set; }
        public string MVP { get; set; }
        public string KDA { get; set; }
        public string 出場次數 { get; set; }
        public string 總擊殺 { get; set; }
        public string 總助攻 { get; set; }
        public string 總死亡 { get; set; }
        public string 場均金錢 { get; set; }
        public string 場均補刀 { get; set; }
        public string 場均差眼 { get; set; }
        public string 場均排眼 { get; set; }
        public string 場均參圖率 { get; set; }
        public string 場均對位經濟差 { get; set; }
        public string 傷害占比 { get; set; }
        public string 經濟占比 { get; set; }
    
        public virtual PlayerList PlayerList { get; set; }
    }
}
