//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerList()
        {
            this.PlayerData = new HashSet<PlayerData>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Account_ID { get; set; }
        public Nullable<long> Age { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string Skill { get; set; }
        public string Exp { get; set; }
        public Nullable<System.DateTime> Join_date { get; set; }
        public Nullable<long> Team_ID { get; set; }
        public byte[] Image { get; set; }
        public string Note { get; set; }
    
        public virtual AccountData AccountData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerData> PlayerData { get; set; }
        public virtual TeamList TeamList { get; set; }
    }
}
